$ANSIBLE_VAULT;1.1;AES256
30306532393330393035353234393738653838663739383234613137616464633838663632396561
6465393436393765333361656235306638306331646562630a326261353731316631333761333834
31326539616131623662373935663837316164366262613963333361393530323631663364396562
3431366564326636350a396363303336666331326165663563343433653131656561346531316637
37343935353264393666306361663133316363303631396639653630343030373966393966353739
39393632643564383934386236653834303362616566376634323834316666353633633530656431
62646130326434346166616131343265653631346435326536373962313862386633616166343166
66353530366465666365653535306133376633353638333963303334343031646632633162633735
30383233323064613436636166373333303536633863373463613339326561643163623839396434
37356364306531396130333336653964313531303939363238346534353636326263646263643039
35623262643736613339336531333263303632666231396565376663306338383666373064323438
61353036343765666338633763336531393762656339343337626532643737616133386366663063
6233
